=== ChibiOS/ChibiOS/tools/ftl/schema/clocks/clocktree.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="clocktree" type="clocktreeType"></xs:element>
    
    <xs:complexType name="clocktreeType">
      <xs:sequence>
            <xs:element name="settings" type="settingsType" maxOccurs="1" minOccurs="1"></xs:element>
            <xs:element name="clocks" type="clocksType" maxOccurs="1"
          minOccurs="1">
        </xs:element>
      </xs:sequence>
    </xs:complexType>

    <xs:complexType name="clocksType">
      <xs:sequence>
        <xs:element name="clock" type="clockType" maxOccurs="unbounded" minOccurs="1"></xs:element>
      </xs:sequence>
    </xs:complexType>
    

    <xs:complexType name="clockType">
      <xs:sequence>
        <xs:element name="description" type="xs:string" maxOccurs="1"
          minOccurs="1">
        </xs:element>
        <xs:element name="bits" type="boolBitsType" maxOccurs="1"
          minOccurs="0">
        </xs:element>
        <xs:choice maxOccurs="1" minOccurs="1">
          <xs:element name="source" type="sourceType" maxOccurs="1"
            minOccurs="1">
          </xs:element>
          <xs:element name="mux" type="muxType" maxOccurs="1" minOccurs="1"></xs:element>
          <xs:element name="divider" type="dividerType" maxOccurs="1"
            minOccurs="1">
          </xs:element>
          <xs:element name="multiplier" type="multiplierType" maxOccurs="1"
            minOccurs="1">
          </xs:element>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="point" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1"></xs:minLength>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="enable" use="required">
        <xs:annotation>
          <xs:documentation>
            Clock point enable policy.
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="never"></xs:enumeration>
            <xs:enumeration value="manual"></xs:enumeration>
            <xs:enumeration value="auto"></xs:enumeration>
            <xs:enumeration value="always"></xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="dynamic" use="required">
        <xs:annotation>
          <xs:documentation>
            Clock point is part of the runtime-switchable dynamic set.
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="yes"></xs:enumeration>
            <xs:enumeration value="no"></xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>

    <xs:complexType name="sourceType">
      <xs:sequence>
        <xs:element name="complex" type="xs:string" maxOccurs="1"
          minOccurs="0">
        </xs:element>
      </xs:sequence>
      <xs:attribute name="frequency" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1"></xs:minLength>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>

    <xs:complexType name="muxType">
      <xs:sequence>
        <xs:element name="input" type="inputType" maxOccurs="unbounded"
          minOccurs="1">
        </xs:element>
      </xs:sequence>
      <xs:attribute name="name" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1"></xs:minLength>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>

    <xs:complexType name="dividerType">
      <xs:choice maxOccurs="1" minOccurs="1">
        <xs:element name="value" type="valueType" maxOccurs="1" minOccurs="1"></xs:element>
        <xs:element name="set" type="setType" maxOccurs="1" minOccurs="1"></xs:element>
        <xs:element name="choices" type="choicesType" maxOccurs="1" minOccurs="1"></xs:element>
      </xs:choice>
      <xs:attribute name="name" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1"></xs:minLength>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="input" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1"></xs:minLength>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>

    <xs:complexType name="multiplierType">
      <xs:choice maxOccurs="1" minOccurs="1">
        <xs:element name="value" type="valueType" maxOccurs="1" minOccurs="1"></xs:element>
        <xs:element name="set" type="setType" maxOccurs="1" minOccurs="1"></xs:element>
        <xs:element name="choices" type="choicesType" maxOccurs="1" minOccurs="1"></xs:element>
      </xs:choice>
      <xs:attribute name="name" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1"></xs:minLength>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="input" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1"></xs:minLength>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>

    <xs:complexType name="inputType">
      <xs:sequence>
        <xs:element name="bits" type="valueBitsType" maxOccurs="1"
          minOccurs="1">
        </xs:element>
      </xs:sequence>
      <xs:attribute name="point" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1"></xs:minLength>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="default" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="yes"></xs:enumeration>
            <xs:enumeration value="no"></xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>

    <xs:complexType name="namesType"></xs:complexType>

    <xs:complexType name="valueBitsType">
      <xs:attribute name="value" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1"></xs:minLength>
            <xs:whiteSpace value="collapse"></xs:whiteSpace>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>

    <xs:complexType name="boolBitsType">
      <xs:attribute name="enabled" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1"></xs:minLength>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="disabled" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1"></xs:minLength>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>

    <xs:complexType name="valueType">
      <xs:sequence>
        <xs:element name="bits" type="valueBitsType" maxOccurs="1"
          minOccurs="1">
        </xs:element>
      </xs:sequence>
      <xs:attribute name="min">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="(0|[1-9][0-9]*|[A-Za-z_][A-Za-z0-9_]*)"></xs:pattern>
            <xs:minLength value="1"></xs:minLength>
            <xs:whiteSpace value="collapse"></xs:whiteSpace>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="max">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1"></xs:minLength>
            <xs:whiteSpace value="collapse"></xs:whiteSpace>
            <xs:pattern value="(0|[1-9][0-9]*|[A-Za-z_][A-Za-z0-9_]*)"></xs:pattern>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="default">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="(0|[1-9][0-9]*|[A-Za-z_][A-Za-z0-9_]*)"></xs:pattern>
            <xs:minLength value="1"></xs:minLength>
            <xs:whiteSpace value="collapse"></xs:whiteSpace>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>

    <xs:complexType name="setType">
      <xs:sequence>
        <xs:element name="bits" type="valueBitsType" maxOccurs="1"
          minOccurs="1">
        </xs:element>
      </xs:sequence>
      <xs:attribute name="values">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="(0|[1-9][0-9]*)([ ,](0|[1-9][0-9]*))*"/>
            <xs:minLength value="1"></xs:minLength>
            <xs:whiteSpace value="collapse"></xs:whiteSpace>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="default">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="(0|[1-9][0-9]*)"></xs:pattern>
            <xs:minLength value="1"></xs:minLength>
            <xs:whiteSpace value="collapse"></xs:whiteSpace>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>

    <xs:complexType name="choicesType">
      <xs:sequence>
        <xs:element name="choice" type="choiceType" maxOccurs="unbounded" minOccurs="1"></xs:element>
      </xs:sequence>
      <xs:attribute name="default">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="(0|[1-9][0-9]*|[A-Za-z_][A-Za-z0-9_]*)"></xs:pattern>
            <xs:minLength value="1"></xs:minLength>
            <xs:whiteSpace value="collapse"></xs:whiteSpace>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>

    <xs:complexType name="choiceType">
      <xs:sequence>
        <xs:element name="bits" type="valueBitsType" maxOccurs="1"
          minOccurs="1">
        </xs:element>
      </xs:sequence>
      <xs:attribute name="item" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1"></xs:minLength>
            <xs:whiteSpace value="collapse"></xs:whiteSpace>
            <xs:pattern value="[A-Za-z_][A-Za-z0-9_]*"></xs:pattern>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="value" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1"></xs:minLength>
            <xs:whiteSpace value="collapse"></xs:whiteSpace>
            <xs:pattern value="0|[1-9][0-9]*"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>

    <xs:complexType name="settingsType">
      <xs:sequence>
        <xs:element name="prefixes" type="prefixesType" maxOccurs="1"
          minOccurs="1">
        </xs:element>
        <xs:element name="suffixes" type="suffixesType" maxOccurs="1" minOccurs="1"></xs:element>
        <xs:element name="configs" type="configsType" maxOccurs="1" minOccurs="1"></xs:element>
      </xs:sequence>
    </xs:complexType>

    <xs:complexType name="configsType">
      <xs:sequence>
        <xs:element name="config" type="configType" maxOccurs="unbounded" minOccurs="1"></xs:element>
      </xs:sequence>
    </xs:complexType>

    <xs:complexType name="configType">
      <xs:sequence>
        <xs:element name="description" type="xs:string" maxOccurs="1"
          minOccurs="1">
        </xs:element>
      </xs:sequence>
      <xs:attribute name="macro" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1"></xs:minLength>
            <xs:whiteSpace value="collapse"></xs:whiteSpace>
            <xs:pattern value="[A-Za-z_][A-Za-z0-9_]*"></xs:pattern>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="bool"></xs:enumeration>
            <xs:enumeration value="value"></xs:enumeration>
            <xs:enumeration value="set"></xs:enumeration>
            <xs:enumeration value="raw"></xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="default" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1"></xs:minLength>
            <xs:whiteSpace value="collapse"></xs:whiteSpace>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="role" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="dynamic_mode"></xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="min" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="(0|[1-9][0-9]*|[A-Za-z_][A-Za-z0-9_]*)"></xs:pattern>
            <xs:minLength value="1"></xs:minLength>
            <xs:whiteSpace value="collapse"></xs:whiteSpace>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="max" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="(0|[1-9][0-9]*|[A-Za-z_][A-Za-z0-9_]*)"></xs:pattern>
            <xs:minLength value="1"></xs:minLength>
            <xs:whiteSpace value="collapse"></xs:whiteSpace>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="values" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="(0|[1-9][0-9]*|[A-Za-z_][A-Za-z0-9_]*)([ ,](0|[1-9][0-9]*|[A-Za-z_][A-Za-z0-9_]*))*"/>
            <xs:minLength value="1"></xs:minLength>
            <xs:whiteSpace value="collapse"></xs:whiteSpace>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>

    <xs:complexType name="prefixesType">
      <xs:attribute name="clock_points" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1"></xs:minLength>
            <xs:whiteSpace value="collapse"></xs:whiteSpace>
            <xs:pattern value="[A-Za-z_][A-Za-z0-9_]*"></xs:pattern>
            <xs:maxLength value="12"></xs:maxLength>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="macros" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1"></xs:minLength>
            <xs:whiteSpace value="collapse"></xs:whiteSpace>
            <xs:pattern value="[A-Za-z_][A-Za-z0-9_]*"></xs:pattern>
            <xs:maxLength value="12"></xs:maxLength>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="cfgs" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1"></xs:minLength>
            <xs:maxLength value="12"></xs:maxLength>
            <xs:whiteSpace value="collapse"></xs:whiteSpace>
            <xs:pattern value="[A-Za-z_][A-Za-z0-9_]*"></xs:pattern>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>

    <xs:complexType name="suffixesType">
      <xs:attribute name="frequency" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:whiteSpace value="collapse"></xs:whiteSpace>
            <xs:pattern value="[A-Za-z_][A-Za-z0-9_]*"></xs:pattern>
            <xs:maxLength value="8"></xs:maxLength>
            <xs:minLength value="1"></xs:minLength>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="values" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:whiteSpace value="collapse"></xs:whiteSpace>
            <xs:pattern value="[A-Za-z_][A-Za-z0-9_]*"></xs:pattern>
            <xs:maxLength value="8"></xs:maxLength>
            <xs:minLength value="1"></xs:minLength>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="bits" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1"></xs:minLength>
            <xs:maxLength value="8"></xs:maxLength>
            <xs:whiteSpace value="collapse"></xs:whiteSpace>
            <xs:pattern value="[A-Za-z_][A-Za-z0-9_]*"></xs:pattern>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="selector" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1"></xs:minLength>
            <xs:maxLength value="8"></xs:maxLength>
            <xs:whiteSpace value="collapse"></xs:whiteSpace>
            <xs:pattern value="[A-Za-z_][A-Za-z0-9_]*"></xs:pattern>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="enable" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1"></xs:minLength>
            <xs:maxLength value="8"></xs:maxLength>
            <xs:whiteSpace value="collapse"></xs:whiteSpace>
            <xs:pattern value="[A-Za-z_][A-Za-z0-9_]*"></xs:pattern>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="enabled" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1"></xs:minLength>
            <xs:maxLength value="8"></xs:maxLength>
            <xs:whiteSpace value="collapse"></xs:whiteSpace>
            <xs:pattern value="[A-Za-z_][A-Za-z0-9_]*"></xs:pattern>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
</xs:schema>

=== ChibiOS/ChibiOS/os/hal/ports/STM32/STM32G4xx_TEST/cfg/clocktree.xml
<clocktree
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="http://www.chibios.org/xml/schema/clocks/clocktree.xsd">
  <settings>
    <prefixes clock_points="CLK_" macros="STM32_" cfgs="STM32_CFG_" />
    <suffixes values="_VALUE" bits="_BITS" selector="_SEL" enable="_ENABLE" />
    <mode macro="STM32_CFG_CLOCK_DYNAMIC" default="FALSE" />
  </settings>
  <clocks>
    <clock point="NONE" enable="never" dynamic="no">
      <description>pseudo-clock for disabled sources</description>
      <source frequency="0U" />
    </clock>
    <clock point="HSI16" enable="manual" dynamic="yes">
      <description>16MHz high speed internal oscillator</description>
      <bits enabled="(RCC_CR_HSIKERON | RCC_CR_HSION)" disabled="0U" />
      <source frequency="16000000U" />
    </clock>
    <clock point="HSI48" enable="manual" dynamic="yes">
      <description>48MHz high speed internal oscillator</description>
      <bits enabled="RCC_CRRCR_HSI48ON" disabled="0U" />
      <source frequency="48000000U" />
    </clock>
    <clock point="HSE" enable="manual" dynamic="yes">
      <description>high frequency external oscillator</description>
      <bits enabled="RCC_CR_HSEON" disabled="0U" />
      <source frequency="STM32_HSECLK" />
    </clock>
    <clock point="LSE" enable="manual" dynamic="no">
      <description>low frequency external oscillator</description>
      <bits enabled="RCC_BDCR_LSEON" disabled="0U" />
      <source frequency="STM32_LSECLK" />
    </clock>
    <clock point="LSI" enable="manual" dynamic="no">
      <description>low frequency internal oscillator</description>
      <bits enabled="RCC_CSR_LSION" disabled="0U" />
      <source frequency="32768U" />
    </clock>
    <clock point="PLLIN" enable="auto" dynamic="no">
      <description>PLL input</description>
      <mux name="PLLSRC">
        <input point="NONE">
          <bits value="STM32_PLLSRC_NOCLOCK" />
        </input>
        <input point="HSI16" default="yes">
          <bits value="STM32_PLLSRC_HSI16" />
        </input>
        <input point="HSE">
          <bits value="STM32_PLLSRC_HSE" />
        </input>
      </mux>
    </clock>
    <clock point="PLLREF" enable="auto" dynamic="no">
      <description>PLL reference</description>
      <divider name="PLLM" input="PLLIN">
        <value min="1" max="16" default="4">
          <bits value="((%N% - 1U) &lt;&lt; RCC_PLLCFGR_PLLM_Pos)" />
        </value>
      </divider>
    </clock>
     <clock point="PLLVCO" enable="auto" dynamic="no">
      <description>PLL VCO</description>
      <multiplier name="PLLN" input="PLLREF">
        <value min="8" max="127" default="84">
          <bits value="(%N% &lt;&lt; RCC_PLLCFGR_PLLN_Pos)" />
        </value>
      </multiplier>
    </clock>
     <clock point="PLLP" enable="auto" dynamic="yes">
      <description>PLL P output</description>
      <bits enabled="RCC_PLLCFGR_PLLPEN" disabled="0U" />
      <divider name="PLLP" input="PLLVCO">
        <value min="2" max="31" default="7">
          <bits value="(%N% &lt;&lt; RCC_PLLCFGR_PLLPDIV_Pos)" />
        </value>
      </divider>
    </clock>
    <clock point="PLLQ" enable="auto" dynamic="yes">
      <description>PLL Q output</description>
      <bits enabled="RCC_PLLCFGR_PLLQEN" disabled="0U" />
      <divider name="PLLQ" input="PLLVCO">
        <set values="2 4 6 8" default="8">
          <bits value="(((%N% / 2U) - 1U) &lt;&lt; RCC_PLLCFGR_PLLQ_Pos)" />
        </set>
      </divider>
    </clock>
    <clock point="PLLR" enable="auto" dynamic="yes">
     <description>PLL R output</description>
      <bits enabled="RCC_PLLCFGR_PLLREN" disabled="0U" />
      <divider name="PLLR" input="PLLVCO">
        <set values="2 4 6 8" default="2">
          <bits value="(((%N% / 2U) - 1U) &lt;&lt; RCC_PLLCFGR_PLLR_Pos)" />
        </set>
      </divider>
    </clock>
    <clock point="SYSCLK" enable="always" dynamic="yes">
      <description>system clock</description>
      <mux name="SW">
        <input point="HSI16">
          <bits value="STM32_SW_HSI16" />
        </input>
        <input point="HSE">
          <bits value="STM32_SW_HSE" />
        </input>
        <input point="PLLR" default="yes">
          <bits value="STM32_SW_PLLRCLK" />
        </input>
      </mux>
    </clock>
    <clock point="HCLK" enable="always" dynamic="yes">
     <description>AHB</description>
      <divider name="HPRE" input="SYSCLK">
        <choices>
          <choice item="DIV1" value="1"><bits value="STM32_HPRE_DIV1" /></choice>
          <choice item="DIV2" value="2"><bits value="STM32_HPRE_DIV2" /></choice>
          <choice item="DIV4" value="4"><bits value="STM32_HPRE_DIV4" /></choice>
          <choice item="DIV8" value="8"><bits value="STM32_HPRE_DIV8" /></choice>
          <choice item="DIV16" value="16"><bits value="STM32_HPRE_DIV16" /></choice>
          <choice item="DIV64" value="64"><bits value="STM32_HPRE_DIV64" /></choice>
          <choice item="DIV128" value="128"><bits value="STM32_HPRE_DIV128" /></choice>
          <choice item="DIV256" value="256"><bits value="STM32_HPRE_DIV256" /></choice>
          <choice item="DIV512" value="512"><bits value="STM32_HPRE_DIV512" /></choice>
        </choices>
      </divider>
    </clock>
    <clock point="PCLK1" enable="always" dynamic="yes">
     <description>APB1</description>
      <divider name="PPRE1" input="HCLK">
        <choices default="2">
          <choice item="DIV1" value="1"><bits value="STM32_PPRE1_DIV1" /></choice>
          <choice item="DIV2" value="2"><bits value="STM32_PPRE1_DIV2" /></choice>
          <choice item="DIV4" value="4"><bits value="STM32_PPRE1_DIV4" /></choice>
          <choice item="DIV8" value="8"><bits value="STM32_PPRE1_DIV8" /></choice>
          <choice item="DIV16" value="16"><bits value="STM32_PPRE1_DIV16" /></choice>
        </choices>
      </divider>
    </clock>
    <clock point="PCLK2" enable="always" dynamic="yes">
     <description>APB2</description>
      <divider name="PPRE2" input="HCLK">
        <choices>
          <choice item="DIV1" value="1"><bits value="STM32_PPRE2_DIV1" /></choice>
          <choice item="DIV2" value="2"><bits value="STM32_PPRE2_DIV2" /></choice>
          <choice item="DIV4" value="4"><bits value="STM32_PPRE2_DIV4" /></choice>
          <choice item="DIV8" value="8"><bits value="STM32_PPRE2_DIV8" /></choice>
          <choice item="DIV16" value="16"><bits value="STM32_PPRE2_DIV16" /></choice>
        </choices>
      </divider>
    </clock>
    <clock point="PCLK1TIM" enable="always" dynamic="yes">
      <description>APB1 timer clock</description>
      <source frequency="((STM32_CFG_PCLK1_VALUE == 1) ? STM32_PCLK1_FREQ : (STM32_PCLK1_FREQ * 2U))" />
    </clock>
    <clock point="PCLK2TIM" enable="always" dynamic="yes">
      <description>APB2 timer clock</description>
      <source frequency="((STM32_CFG_PCLK2_VALUE == 1) ? STM32_PCLK2_FREQ : (STM32_PCLK2_FREQ * 2U))" />
    </clock>
    <clock point="CKIN" enable="always" dynamic="no">
      <description>external audio clock input</description>
      <source frequency="0U" />
    </clock>
    <clock point="HSEDIV" enable="always" dynamic="no">
      <description>HSE divided clock</description>
      <source frequency="(STM32_HSE_FREQ / 32U)" />
    </clock>
    <clock point="MCODIV" enable="always" dynamic="no">
      <description>MCO source before prescaler</description>
      <mux name="MCOSEL">
        <input point="NONE" default="yes"><bits value="STM32_MCOSEL_NOCLOCK" /></input>
        <input point="SYSCLK"><bits value="STM32_MCOSEL_SYSCLK" /></input>
        <input point="HSI16"><bits value="STM32_MCOSEL_HSI16" /></input>
        <input point="HSE"><bits value="STM32_MCOSEL_HSE" /></input>
        <input point="PLLR"><bits value="STM32_MCOSEL_PLLRCLK" /></input>
        <input point="LSI"><bits value="STM32_MCOSEL_LSI" /></input>
        <input point="LSE"><bits value="STM32_MCOSEL_LSE" /></input>
        <input point="HSI48"><bits value="STM32_MCOSEL_HSI48" /></input>
      </mux>
    </clock>
    <clock point="MCO" enable="always" dynamic="yes">
      <description>MCO output pin</description>
      <divider name="MCOPRE" input="MCODIV">
        <choices>
          <choice item="DIV1" value="1"><bits value="STM32_MCOPRE_DIV1" /></choice>
          <choice item="DIV2" value="2"><bits value="STM32_MCOPRE_DIV2" /></choice>
          <choice item="DIV4" value="4"><bits value="STM32_MCOPRE_DIV4" /></choice>
          <choice item="DIV8" value="8"><bits value="STM32_MCOPRE_DIV8" /></choice>
          <choice item="DIV16" value="16"><bits value="STM32_MCOPRE_DIV16" /></choice>
        </choices>
      </divider>
    </clock>
    <clock point="LSCO" enable="always" dynamic="no">
      <description>LSCO output pin</description>
      <mux name="LSCOSEL">
        <input point="NONE" default="yes"><bits value="STM32_LSCOSEL_NOCLOCK" /></input>
        <input point="LSI"><bits value="STM32_LSCOSEL_LSI" /></input>
        <input point="LSE"><bits value="STM32_LSCOSEL_LSE" /></input>
      </mux>
    </clock>
    <clock point="RTC" enable="always" dynamic="no">
      <description>RTC</description>
      <mux name="RTCSEL">
        <input point="NONE" default="yes"><bits value="STM32_RTCSEL_NOCLOCK" /></input>
        <input point="LSE"><bits value="STM32_RTCSEL_LSE" /></input>
        <input point="LSI"><bits value="STM32_RTCSEL_LSI" /></input>
        <input point="HSEDIV"><bits value="STM32_RTCSEL_HSEDIV" /></input>
      </mux>
    </clock>
    <clock point="USART1" enable="always" dynamic="no">
      <description>USART1</description>
      <mux name="USART1SEL">
        <input point="PCLK2"><bits value="STM32_USART1SEL_PCLK2" /></input>
        <input point="SYSCLK" default="yes"><bits value="STM32_USART1SEL_SYSCLK" /></input>
        <input point="HSI16"><bits value="STM32_USART1SEL_HSI16" /></input>
        <input point="LSE"><bits value="STM32_USART1SEL_LSE" /></input>
      </mux>
    </clock>
